#include "kernel/generic/axpby_device.cuh"
#include "kernel/generic/gather_device.cuh"
#include "kernel/generic/rot_device.cuh"
#include "kernel/generic/spvv_device.cuh"
#include "kernel/generic/scatter_device.cuh"
